### PR TITLE
Do not throw exception when Correlation accessor has Context as null

### PR DESCRIPTION
**Pull request by VKAlwaysWin**

### CODE REVIEW

**Comment by Herlitzd** [comment]
I would love to see this merged, we are blocked by this.

Our application sometimes uses HttpClients from WebRequests, and sometimes they get invoked by a Queue Consumer, the invocations from the Consumer Null Ref out.

**Comment by anilkutahyali** [comment]
I am writing integration tests, but I get errors because of this issue.

**Comment by nover** [comment]
we're also having problems with this - any chance of getting it merged soon?

**Comment by VKAlwaysWin** [comment]
@stevejgordon any chance that we can get this PR ?

**Review by stevejgordon — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
